#!/bin/sh

readonly prefix_path=$(dirname ${0})
readonly conf_name=$(basename ${0})

source ${prefix_path}/librootfs.sh


rootfs__add_packages \
  apk-tools \
  alpine-mirrors \
  kbd-bkeymaps \
  chrony \
  e2fsprogs \
  haveged \
  network-extras \
  openssl \
  openssh \
  sudo \
  tzdata

rootfs__enable_services_on sysinit \
  devfs \
  dmesg \
  hwdrivers \
  mdev

rootfs__enable_services_on boot \
  bootmisc \
  hostname \
  modules \
  swclock \
  sysctl \
  syslog

rootfs__enable_services_on shutdown \
  killprocs \
  mount-ro \
  savecache

rootfs__add_overlay_from ${conf_name}

adduser \
    -D \
    alpine \
  && echo "alpine:alpine" \
     |chpasswd \
  && addgroup sudo \
  && adduser alpine sudo \
  && echo -e "\n# Allow sudo without password\n%sudo ALL=(ALL) NOPASSWD:ALL\n" >> /etc/sudoers
