#!/bin/sh

readonly prefix_path=$(dirname ${0})
readonly conf_name=$(basename ${0})

source ${prefix_path}/librootfs.sh


rootfs__add_packages \
  apk-tools \
  alpine-mirrors \
  kbd-bkeymaps \
  e2fsprogs \
  haveged \
  network-extras \
  openssl \
  tzdata

rootfs__enable_services_on sysinit \
  devfs \
  dmesg \
  hwdrivers \
  mdev

rootfs__enable_services_on boot \
  bootmisc \
  hostname \
  modules \
  swclock \
  sysctl \
  syslog

rootfs__enable_services_on shutdown \
  killprocs \
  mount-ro \
  savecache

rootfs__add_overlay_from ${conf_name}

